
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import Nav from "../../../components/navigation";
//import Nav from '../../../components/navigation.jsx';
import Nav from "../../components/navigation";
//import SessionProviderWrapper from "../../../components/SessionProviderWrapper";
import SessionProviderWrapper from "../../components/SessionProviderWrapper";
import CartProviderWrapper from "../../components/cartProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <SessionProviderWrapper>
          <CartProviderWrapper>
              <Nav/>
            {children}
          </CartProviderWrapper>
         </SessionProviderWrapper>
        </body>
    </html>
  );
}
